#!/bin/zsh

LIBRARY_PREFERENCES_PATH="$HOME/Library/Preferences"
MYMAC_PLIST_PATH=$(dirname $0)/../config/plist

cd $MYMAC_PLIST_PATH

for plist (*.plist) {
    chmod 600 "$plist"
    echo "remove $LIBRARY_PREFERENCES_PATH/$plist"
    rm "$LIBRARY_PREFERENCES_PATH/$plist"
    echo "copy $MYMAC_PLIST_PATH/$plist => $LIBRARY_PREFERENCES_PATH/$plist"
    cp "$plist" "$LIBRARY_PREFERENCES_PATH/$plist"
}

defaults read com.googlecode.iterm2 >/dev/null

